export { default as DrivingInfoPage } from './pages/InfoPage'
export { default as DrivingTestPage } from './pages/TestPage'
export { default as DrivingInstructionPage } from './pages/InstructionPage'
export { default as DrivingRegisterPage } from './pages/RegisterPage'
export { default as B2InfoPage } from './pages/B2InfoPage'
export { default as DrivingHealthPage } from './pages/HealthPage'
