export { default as AdminBicyclePage } from './bicycle/BicycleAdminPage'
export { default as AdminDrivingPage } from './driving-license/DrivingAdminPage'
export { default as AdminGuestHousePage } from './guest-house/GuestHouseAdminPage'
export { default as AdminGuidePage } from './guide/GuideAdminPage'
export { default as AdminHealthPage } from './health/HealthAdminPage'
export { default as AdminLoginPage } from './auth/LoginPage'
export { default as AdminSignupPage } from './auth/SignupPage'
